# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bommen
# "service" is the name of this project. This will also be added to your AWS resource names.
service: solbeen-shui

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::713881809194:role/lecture-role
  httpApi:
    cors: true

  package:
    individually: true


functions:
  getMsgs:
    handler: functions/getMsgs/index.handler
    events:
      - httpApi:
          path: /
          method: GET

  writeMsg:
    handler: functions/writeMsg/index.handler
    events:
      - httpApi:
          path: /
          method: POST

  updateMsg:
    handler: functions/updateMsg/index.handler
    events:
      - httpApi:
          path: /message/{id}
          method: PUT  

  deleteMsg:
    handler: functions/deleteMsg/index.handler
    events:
      - httpApi:
          path: /message/{id}
          method: DELETE 

resources:
  Resources:
    MessageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my-messages
        AttributeDefinitions:
          - AttributeName: 'messageId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'messageId'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

